### ISSUE TITLE
Remove foreground operations in maintain function

### ISSUE THREAD

**Issue by DuckLL** [js4jiang5/BatteryOptimizer_for_MAC#5]
https://github.com/js4jiang5/BatteryOptimizer_for_MAC/blob/27f3e723a55ac35ca8cb1d4edb06351e5305a8d8/battery.sh#L1126-L1135

I recommend removing this function. In my view, the `maintain` function should be limited to configuration settings only, without performing any foreground operations.
However, there may be considerations I'm not aware of, so feel free to share if there's a specific reason for including it.

**Comment by js4jiang5** [comment]
That's because users usually raise a question - "I've already set the limit to 80, why is it still at 100 ???"
In original battery app, it provides the third argument "--force_discharge", but that is cumbersome and not revealed to users, so I decide to make an interaction dialog to let users decide. If users don't make their mind after 10 secs, I decide for them to discharge.
In original battery app, there're two functions, "maintain" and "maintain_synchronous". The first is for users to run in terminal, and the second is called in background when reboot. Therefore, I think "maintain" is designed to be used in foreground, while "maintain_synchronous" is limited to configuration settings only.
